Repository Server-Starter-for-Minecraft/ServerStarter2, pull requests merged in 2023-12, with the labels that each got.

#67 ZIP形式のMODに対応
  src-electron/core/world/dialog.ts
  src-electron/core/world/files/addtional/mod.ts
Labels: enhancement, ■Backend

#65 API.OpenFolderにautocreate引数を追加して使用
  src-electron/api/api.ts
  src-electron/tools/shell.ts
  src-electron/util/error/schema/data.ts
  src/components/World/Contents/ContentsView.vue
  src/i18n/en-US/Other/error.ts
  src/i18n/ja/Other/error.ts
Labels: bug, ■Backend

#70 サーバープロパティの検索アルゴリズムを修正
  src/scripts/objFillter.ts
  src/stores/WorldTabs/PropertyStore.ts
Labels: bug

#75 latest.logの内容を取得する機能を追加
  src-electron/api/api.ts
  src-electron/core/misc/tempPath.ts
  src-electron/core/server/server.ts
  src-electron/core/world/handler.ts
  src-electron/core/world/loghandler.ts
  src-electron/core/world/world.ts
  src-electron/electron-preload.ts
  src-electron/ipc/back.ts
  src-electron/util/awaitOnce.ts
  src-electron/util/dateFormatter.ts
  src-electron/util/error/schema/core.ts
  src-electron/util/gz.ts
  src-electron/util/path.ts
  src/components/MainLayout/WorldTab.vue
  src/components/World/Console/OperationView.vue
  src/components/World/Console/RunningView.vue
  src/components/World/Console/StopView.vue
  src/components/World/HOME/RunningBtn.vue
  src/components/World/HeaderView.vue
  src/i18n/en-US/Other/error.ts
  src/i18n/en-US/Other/general.ts
  src/i18n/en-US/Pages/World/console.ts
  src/i18n/ja/Other/error.ts
  src/i18n/ja/Other/general.ts
  src/i18n/ja/Pages/World/console.ts
  src/stores/ConsoleStore.ts
Labels: enhancement, ■Backend, ■Frontend
