Repository Server-Starter-for-Minecraft/ServerStarter2, pull requests merged in 2024-02, with the labels that each got.

#123 Orginizationのメンバー以外の人がPRを出した場合AutoAssignしない
  .github/workflows/auto_assign.yml
Labels: :arrow_lower_right: Low Priority

#136 SetWorldにおいてCustomMapを導入する処理場合に限りAdditional設定を反映しない
  src-electron/core/world/local.ts
Labels: bug, ■Backend

#120 🐛 Fixed #80
  src/pages/SystemSettings/InfoPage.vue
Labels: ■Frontend

#139 ワールドの複製後にダイアログが消えるように修正
  src/components/MainLayout/CustomMapImporter/checkDialog.vue
  src/components/MainLayout/RecoverDialog/RecoverDialog.vue
  src/components/SystemSettings/General/OwnerSetter/OwnerDialog.vue
  src/components/SystemSettings/Remote/NewRemoteDialog.vue
  src/components/World/ShareWorld/selecters/github/ExistedGitHubDialog.vue
  src/components/World/ShareWorld/selecters/github/NewGitHubDialog.vue
  src/pages/WorldTabs/HomePage.vue
Labels: ■Frontend, :fire: High Priority

#122 ビルドスクリプトが更新をmainに直接pushしない
  .github/release-drafter.yml
  .github/workflows/build.yml
Labels: development

#110 ビルド時にvcruntimeを組み込む
  include/vcruntime140.dll
  quasar.config.js
  src-electron/core/server/setup/ngrok.ts
Labels: bug, ■Backend

#143 🚑 システムが最新かどうかを比較するバージョン文字列に接頭辞"v"をつける
  src-electron/updater/fetch.ts
  src-electron/updater/updater.ts
Labels: ■Backend, :fire: High Priority

#114 Linux上でのビルドと起動
  package.json
  quasar.config.js
Labels: enhancement

#150 NgrokのbinPath引数を削除
  src-electron/core/server/setup/ngrok.ts
Labels: ■Backend, :fire: High Priority

#152 gitmojiをはじめとするワークスペース設定の更新
  .prettierrc
  .vscode/extensions.json
  .vscode/settings.json
Labels: development
