Repository Server-Starter-for-Minecraft/ServerStarter2, pull requests merged in 2024-03, with the labels that each got.

#157 システム設定にスクロールバーを設定
  src/css/app.scss
  src/pages/SystemSettings/GeneralPage.vue
  src/pages/SystemSettings/InfoPage.vue
Labels: enhancement, ■Frontend

#156 ワールド検索機能の強化
  src/scripts/textUtils.ts
  src/stores/MainStore.ts
Labels: ■Frontend

#133 危険性のある操作に対する警告を追加
  src/components/MainLayout/NewWorldBtn.vue
  src/components/MainLayout/RecoverDialog/RecoverDialog.vue
  src/components/World/Contents/itemCardView.vue
  src/components/World/HOME/Top/VersionSelecter/FabricView.vue
  src/components/World/HOME/Top/VersionSelecter/ForgeView.vue
  src/components/World/HOME/Top/VersionSelecter/MohistMCView.vue
  src/components/World/HOME/Top/VersionSelecter/PaperMCView.vue
  src/components/World/HOME/Top/VersionSelecter/SpigotView.vue
  src/components/World/HOME/Top/VersionSelecter/VanillaView.vue
  src/components/World/HOME/Top/VersionSelecter/versionComparator.ts
  src/components/World/HOME/Top/VersionSelecterView.vue
  src/components/util/danger/DangerDialog.vue
  src/i18n/en-US/Pages/World/additionalContents.ts
  src/i18n/en-US/Pages/World/home.ts
  src/i18n/ja/Pages/World/additionalContents.ts
  src/i18n/ja/Pages/World/home.ts
  src/i18n/utils/tFunc.ts
  src/init.ts
  src/scripts/obj.ts
  src/stores/ConsoleStore.ts
  src/stores/MainStore.ts
  src/stores/WorldTabs/ContentsStore.ts
Labels: ■Frontend

#161 linuxのビルド版にアイコンを設定する
  quasar.config.js
Labels: :fire: High Priority
