Repository Server-Starter-for-Minecraft/ServerStarter2, pull requests merged in 2024-05, with the labels that each got.

#158 自動アップデートに際してダイアログを表示する
  src-electron/api/api.ts
  src-electron/core/api.ts
  src-electron/core/user/launcher/launcherProfile.ts
  src-electron/electron-preload.ts
  src-electron/ipc/back.ts
  src-electron/ipc/front.ts
  src-electron/lifecycle/lifecycle.ts
  src-electron/updater/fetch.ts
  src-electron/updater/notify.ts
  src-electron/updater/updater.ts
  src-electron/util/java/java.ts
  src-electron/util/os.ts
  src-electron/util/shutdown.ts
  src/App.vue
  src/components/App/UpdateNotify/UpdateNotifyDialog.vue
  src/components/App/UpdateNotify/iUpdateNotifyDialog.ts
  src/i18n/en-US/Dialogs/updater.ts
  src/i18n/en-US/index.ts
  src/i18n/ja/Dialogs/updater.ts
  src/i18n/ja/index.ts
Labels: enhancement, ■Backend, ■Frontend

#159 ワールド一覧の描画ルールを変更
  src/components/MainLayout/NewWorldBtn.vue
  src/components/MainLayout/WorldList.vue
  src/components/SystemSettings/Folder/FolderCard.vue
  src/components/World/HOME/Others/WorldDeleteView.vue
  src/components/World/Others/WorldFolderView.vue
  src/components/World/SearchWorldView.vue
  src/i18n/en-US/Pages/mainLayout.ts
  src/i18n/ja/Pages/mainLayout.ts
  src/init.ts
  src/pages/WorldPage.vue
  src/stores/MainStore.ts
Labels: enhancement, ■Frontend

#172 ビルドスクリプトを更新
  .github/workflows/build.yml
Labels: development

#174 🚑️ ビルドスクリプトの更新に合わせてquasar.configを修正
  quasar.config.js
Labels: development

#171 🍱 文字入りロゴを出力
  design/Logo.afdesign
  design/icons/logo/Logo.png
  design/icons/logo/with_title/ServerStarterLogo_Black_1.png
  design/icons/logo/with_title/ServerStarterLogo_Black_1.svg
  design/icons/logo/with_title/ServerStarterLogo_Black_2.png
  design/icons/logo/with_title/ServerStarterLogo_Black_2.svg
  design/icons/logo/with_title/ServerStarterLogo_Black_3.png
  design/icons/logo/with_title/ServerStarterLogo_Black_3.svg
  design/icons/logo/with_title/ServerStarterLogo_Black_4.png
  design/icons/logo/with_title/ServerStarterLogo_Black_4.svg
  design/icons/logo/with_title/ServerStarterLogo_White_1.png
  design/icons/logo/with_title/ServerStarterLogo_White_1.svg
  design/icons/logo/with_title/ServerStarterLogo_White_2.png
  design/icons/logo/with_title/ServerStarterLogo_White_2.svg
  design/icons/logo/with_title/ServerStarterLogo_White_3.png
  design/icons/logo/with_title/ServerStarterLogo_White_3.svg
  design/icons/logo/with_title/ServerStarterLogo_White_4.png
  design/icons/logo/with_title/ServerStarterLogo_White_4.svg
Labels: development

#189 'src-public'フォルダを作成
  .prettierrc
  .vscode/settings.json
  src-public/schema/.gitkeep
  src-public/scripts/createNewName.ts
  src-public/scripts/deepcopy.ts
  src-public/scripts/error.ts
  src-public/scripts/obj/obj.ts
  src-public/scripts/obj/objFillter.ts
  src-public/scripts/obj/objFlatten.ts
  src-public/scripts/obj/objSort.ts
  src-public/scripts/obj/objmap.ts
  src-public/scripts/sleep.ts
  src/App.vue
  src/color/index.ts
  src/components/Error/Error.ts
  src/components/Error/ErrorDialogView.vue
  src/components/MainLayout/CustomMapImporter/iCustomMapImporter.ts
  src/components/MainLayout/WorldList.vue
  src/components/SystemSettings/General/AutoShutdown/AutoShutdownDialog.vue
  src/components/SystemSettings/Remote/github/GithubCard.vue
  src/components/World/HOME/Others/WorldDeleteView.vue
  src/components/World/HOME/Top/VersionSelecter/versionComparator.ts
  src/components/World/HOME/Top/WorldNameView.vue
  src/components/World/Others/WorldFolderView.vue
  src/components/World/Player/GroupEditorView.vue
  src/components/World/Player/OpSetterView.vue
  src/components/World/Player/PlayerCardView.vue
  src/components/World/Player/SearchResultView.vue
  src/components/World/Player/SelectedPlayersView.vue
  src/components/World/Property/SideMenuView.vue
  src/components/World/SearchWorldView.vue
  src/components/World/ShareWorld/selecters/github/ExistedGitHubDialog.vue
  src/components/World/ShareWorld/selecters/github/NewGitHubDialog.vue
  src/components/World/ShareWorld/selecters/iRemoteSelecter.ts
  src/i18n/utils/tFunc.ts
  src/init.ts
  src/pages/WorldPage.vue
  src/pages/WorldTabs/PlayerPage.vue
  src/pages/WorldTabs/PropertyPage.vue
  src/stores/ConsoleStore.ts
  src/stores/MainStore.ts
  src/stores/WorldTabs/PlayerStore.ts
  src/stores/WorldTabs/PropertyStore.ts
  tsconfig.json
Labels: ■Frontend
