Repository Server-Starter-for-Minecraft/ServerStarter2, pull requests merged in 2024-01, with the labels that each got.

#77 軽微なUIの問題を修正
  src/components/MainLayout/WorldList.vue
  src/components/MainLayout/WorldTab.vue
  src/components/World/Console/RunningView.vue
  src/components/World/HeaderView.vue
  src/components/World/Others/BootSettingsView.vue
  src/components/World/SearchWorldView.vue
  src/components/util/danger/dangerView.vue
  src/css/app.scss
  src/i18n/en-US/Pages/World/player.ts
  src/i18n/ja/Pages/World/player.ts
  src/pages/SystemSettings/GeneralPage.vue
  src/pages/WorldTabs/HomePage.vue
  src/pages/WorldTabs/OthersPage.vue
  src/pages/WorldTabs/PlayerPage.vue
Labels: bug, ■Frontend

#53 ポート開放不要化機能の追加
  package.json
  src-electron/api/api.ts
  src-electron/core/fixers/ngrok.ts
  src-electron/core/fixers/system.ts
  src-electron/core/fixers/world.ts
  src-electron/core/remote/github/getWorlds.ts
  src-electron/core/server/server.ts
  src-electron/core/server/setup/ngrok.ts
  src-electron/core/world/files/json.ts
  src-electron/core/world/handler.ts
  src-electron/core/world/local.ts
  src-electron/core/world/world.ts
  src-electron/schema/ngrok.ts
  src-electron/schema/remote.ts
  src-electron/schema/server.ts
  src-electron/schema/system.ts
  src-electron/schema/world.ts
  src-electron/util/error/schema/index.ts
  src-electron/util/error/schema/lib.ts
  src/App.vue
  src/assets/assets.ts
  src/assets/captured/Ngrok/mcInput.png
  src/assets/captured/Ngrok/signUp.png
  src/assets/captured/Ngrok/verifyEmail.png
  src/assets/captured/Ngrok/welcome.png
  src/components/World/Console/StopView.vue
  src/components/World/HOME/Others/Ngrok/NgrokSettingDialog.vue
  src/components/World/HOME/Others/Ngrok/steps/Step1View.vue
  src/components/World/HOME/Others/Ngrok/steps/Step2View.vue
  src/components/World/HOME/Others/Ngrok/steps/Step3View.vue
  src/components/World/HOME/Others/Ngrok/steps/iNgrok.ts
  src/components/World/HOME/Others/Ngrok/steps/slides/BaseCard.vue
  src/components/World/HOME/Others/Ngrok/steps/slides/ImgDialog.vue
  src/components/World/HOME/Others/NgrokView.vue
  src/components/World/HeaderView.vue
  src/components/util/danger/dangerView.vue
  src/i18n/en-US/Other/error.ts
  src/i18n/en-US/Other/general.ts
  src/i18n/en-US/Pages/World/home.ts
  src/i18n/ja/Other/error.ts
  src/i18n/ja/Other/general.ts
  src/i18n/ja/Pages/World/home.ts
  src/pages/WorldTabs/HomePage.vue
  src/stores/ConsoleStore.ts
  src/stores/MainStore.ts
  src/stores/WorldTabs/PropertyStore.ts
  yarn.lock
Labels: enhancement, ■Backend, ■Frontend

#79 Tooltipを追加
  src/components/MainLayout/NewWorldBtn.vue
  src/components/MainLayout/WorldList.vue
  src/components/MainLayout/WorldTab.vue
  src/components/Progress/ProgressView.vue
  src/components/SystemSettings/Folder/AddFolderDialog.vue
  src/components/SystemSettings/Folder/FolderCard.vue
  src/components/SystemSettings/General/ColorThemeBtn.vue
  src/components/SystemSettings/General/PlayerCard.vue
  src/components/SystemSettings/Remote/github/GithubCard.vue
  src/components/World/Console/ReadyView.vue
  src/components/World/Console/StopView.vue
  src/components/World/Contents/itemCardView.vue
  src/components/World/HOME/RunningBtn.vue
  src/components/World/HeaderView.vue
  src/components/World/Player/GroupCardView.vue
  src/components/World/Player/GroupEditorView.vue
  src/components/World/Player/PlayerCardView.vue
  src/components/World/Player/SelectedPlayersView.vue
  src/components/World/Player/utils/GroupBadgeView.vue
  src/components/World/Player/utils/PlayerIconInList.vue
  src/components/World/Player/utils/SearchResultItem.vue
  src/components/World/Property/SettingBlockView.vue
  src/components/World/SearchWorldView.vue
  src/components/World/utils/BaseActionsCard.vue
  src/components/World/utils/IconButtonView.vue
  src/components/World/utils/IconTabDropdownView.vue
  src/components/World/utils/IconTabView.vue
  src/components/util/AddContentsCard.vue
  src/components/util/WorldItem.vue
  src/components/util/base/ssTooltip.vue
  src/components/util/danger/DangerDialog.vue
  src/components/util/iconButton.vue
  src/css/app.scss
  src/i18n/en-US/Pages/World/console.ts
  src/i18n/en-US/Pages/World/home.ts
  src/i18n/en-US/Pages/World/others.ts
  src/i18n/en-US/Pages/World/player.ts
  src/i18n/ja/Pages/World/console.ts
  src/i18n/ja/Pages/World/home.ts
  src/i18n/ja/Pages/World/others.ts
  src/i18n/ja/Pages/World/player.ts
  src/pages/ProgressPage.vue
  src/pages/WorldTabs/ConsolePage.vue
  src/pages/WorldTabs/HomePage.vue
Labels: ■Frontend

#86 FolderCardの挙動を修正
  src/components/SystemSettings/Folder/FolderCard.vue
Labels: bug, ■Frontend, :fire: High Priority

#93 NgrokTokenを設定していない場合ワールドのUseNgrokを無視
  src-electron/core/fixers/ngrok.ts
  src-electron/core/world/handler.ts
  src/components/World/HOME/Others/Ngrok/NgrokSettingDialog.vue
  src/components/World/HOME/Others/Ngrok/steps/Step3View.vue
  src/components/World/HOME/Others/Ngrok/steps/iNgrok.ts
  src/components/World/HOME/Others/NgrokView.vue
  src/i18n/en-US/Pages/World/home.ts
  src/i18n/ja/Pages/World/home.ts
  src/stores/MainStore.ts
Labels: ■Backend, :fire: High Priority

#95 本体ログフォルダを開けるようにする。
  src-electron/core/resource.ts
  src-electron/schema/static.ts
  src/i18n/en-US/Pages/systemsetting.ts
  src/i18n/ja/Pages/systemsetting.ts
  src/pages/SystemSettings/InfoPage.vue
Labels: enhancement, ■Backend, ■Frontend

#105 Readme.mdのリンクを更新
  README.md
Labels: enhancement

#109 ビルド用のgithub actionsを作成
  .github/release-drafter.yml
  .github/workflows/build.yml
Labels: development
